project:
  root: "."  

downsample_timestep: 4
rain_event_padding_hours: 2
rainfall_time_step: "15s"

DATA_DIR: "data"
RESULTS_DIR: "results"
  
rainfall:
  data_dir: "data/rainfall"
  results_dir: "results/rainfall"
  csv_pattern: "data/rainfall/rainfall_*.csv"
  runoff_dates:
    "2000_2006": "data/dates_of_runoff_events_2000_2006.csv"
    "2007_2014": "data/dates_of_runoff_events_2007_2014.csv"
    "2015_2024": "data/dates_of_runoff_events_2015_2024.csv"
  runoff_events_nc:
    "2000_2006": "data/runoff_events_2000_2006.nc"
    "2007_2014": "data/runoff_events_2007_2014.nc"
    "2015_2024": "data/runoff_events_2015_2024.nc"
  
  flume_raingauges_file: "data/rainfall/newdata/flume_raingauges.csv"
  downsample_timestep: 4
  rain_event_padding_hours: 2
  rainfall_time_step: "15s"

runoff:
  data_dir: "data/runoff"
  results_dir: "results/runoff"
  files:
    - "data/runoff/runoff_data_2000_2006.csv"
    - "data/runoff/runoff_data_2007_2013.csv"
    - "data/runoff/runoff_data_2014_2024.csv"

min_runoff_cfs: 1.0
  

plotting:
  cluster_labels:
    "1": "cluster 1"
    "2": "cluster 2"
    "3": "cluster 3"
    "4": "cluster 4"
  flume_order:
    - "105"
    - "106"
    - "112"
    - "102"
    - "103"
    - "104"
    - "121"
    - "125"
    - "113"
    - "4"
    - "11"
    - "3"
    - "7"
    - "10"
    - "15"
    - "9"
    - "6"
    - "2"
    - "1"
